version: "3.9"

services:
  paddleocr:
    build: .
    container_name: paddleocr_win
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    shm_size: "8g"
    restart: unless-stopped

    # 关键：启用 GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: "all"          # 或者写成 1 / 2 指定卡数
              capabilities: ["gpu"]
